### ISSUE TITLE
viacep retorna 'erro' ao invés de 'error'

### ISSUE THREAD

**Issue by andrekutianski** [vsilva472/jquery-viacep#2]
Olá, primeiramente obrigado pela excelente biblioteca!

Notei que o ViaCEP retorna a mensagem `erro` ao invés de `error` como o descrito no evento `viacep.response.error`.

Retorno do ViaCEP quando erro no CEP:
```json
{
  "erro": true
}
```

Por ventura esta diferença no nome da chave retorna influencia no evento em questão? (disparar ou não)

Estou tendo problemas em disparar o evento `viacep.response.error`,  sempre eestá retornando o sucesso, mesmo o CEP sendo inválido.

**Comment by vsilva472** [comment]
Olá amigo, obrigado pelo seu report!

Respondendo a sua pergunta, sim faz toda diferença no disparo do evento  de sucesso ou erro e por isso vocẽ estava tendo esse falso positivo. Estou lançanco o fix para este problema e atualize seu projeto para utilizar a versão *1.0.3* do plugin o mais rápido possível.

Novamente obrigado pelo report!
